################################################################################################################
# For additional configurable services, features, and property descriptions,                                   #
# please review class NetworkConfig reference in our TypeDoc:                                                  #
# https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.NetworkConfig.html #
################################################################################################################

homeRegion: &HOME_REGION us-gov-west-1
#####################################
# Delete default VPCs-- use this    #
# object to delete default VPCs in  #
# any non-excluded accounts         #
#####################################
defaultVpc:
  delete: false
  excludeAccounts: []

# Transit Gateway Configurations
transitGateways:
  - name: Network-Main
    account: Network
    region: *HOME_REGION
    shareTargets:
      organizationalUnits:
        - Infrastructure
        - Testing
        - Production

    asn: 65521
    dnsSupport: enable
    vpnEcmpSupport: enable
    defaultRouteTableAssociation: disable
    defaultRouteTablePropagation: disable
    autoAcceptSharingAttachments: enable
    # Adding transit gateway route tables
    routeTables:
      - name: Network-Main-Internal
        routes: []
      - name: Network-Main-Network-Boundary
        routes: []
      - name: Network-Main-SharedServices-Main
        routes: []

#####################################
# Endpoint policies -- use this     #
# object to define standard policies #
# for VPC endpoints                 #
#####################################
endpointPolicies: []

#####################################
# VPCs-- use this object to deploy  #
# a VPC in a single account and     #
# region.                           #
#####################################
vpcs:
  #RFC 1918 Range
  # 10.0.0.0 - 10.255.255.255 (10/8 prefix)
  # 172.16.0.0 - 172.31.255.255 (172.16/12 prefix)
  # 192.168.0.0 - 192.168.255.255 (192.168/16 prefix)
  # Replace the vpc and subnet cidr ranges based on the requirements

  # Network Account
  # Deploys the Network-Boundary VPC
  # Creates 4 subnets in each AZs
  # Subnets includes untrust, trust, management and tgw attach
  # This vpc host firewall appliances
  - name: Network-Boundary
    account: Network
    region: *HOME_REGION
    cidrs:
      - 10.0.0.0/19
    internetGateway: true
    enableDnsHostnames: true
    enableDnsSupport: true
    instanceTenancy: default
    routeTables:
      - name: Network-Boundary-Untrust-Rt-A
        routes:
          - name: TgwRoute
            destination: 10.0.0.0/8
            type: transitGateway
            target: Network-Main
          - name: IgwRoute
            destination: 0.0.0.0/0
            type: internetGateway
            target: IGW
      - name: Network-Boundary-Untrust-Rt-B
        routes:
          - name: TgwRoute
            destination: 10.0.0.0/8
            type: transitGateway
            target: Network-Main
          - name: IgwRoute
            destination: 0.0.0.0/0
            type: internetGateway
            target: IGW
      - name: Network-Boundary-Trust-Rt-A
      - name: Network-Boundary-Trust-Rt-B
      - name: Network-Boundary-Management-Rt-A
        routes:
          - name: IgwRoute
            destination: 0.0.0.0/0
            type: internetGateway
            target: IGW
      - name: Network-Boundary-Management-Rt-B
        routes:
          - name: IgwRoute
            destination: 0.0.0.0/0
            type: internetGateway
            target: IGW
      - name: Network-Boundary-TgwAttach-Rt-A
        routes:
          - name: NatRoute
            destination: 0.0.0.0/0
            type: natGateway
            target: Network-Boundary-NatGw-A
      - name: Network-Boundary-TgwAttach-Rt-B
        routes:
          - name: NatRoute
            destination: 0.0.0.0/0
            type: natGateway
            target: Network-Boundary-NatGw-B
    subnets:
      - name: Network-Boundary-Untrust-A
        availabilityZone: a
        routeTable: Network-Boundary-Untrust-Rt-A
        ipv4CidrBlock: 10.0.0.0/22
      - name: Network-Boundary-Untrust-B
        availabilityZone: b
        routeTable: Network-Boundary-Untrust-Rt-B
        ipv4CidrBlock: 10.0.4.0/22
      - name: Network-Boundary-Trust-A
        availabilityZone: a
        routeTable: Network-Boundary-Trust-Rt-A
        ipv4CidrBlock: 10.0.12.0/22
      - name: Network-Boundary-Trust-B
        availabilityZone: b
        routeTable: Network-Boundary-Trust-Rt-B
        ipv4CidrBlock: 10.0.16.0/22
      - name: Network-Boundary-Management-A
        availabilityZone: a
        routeTable: Network-Boundary-Management-Rt-A
        ipv4CidrBlock: 10.0.24.0/27
      - name: Network-Boundary-Management-B
        availabilityZone: b
        routeTable: Network-Boundary-Management-Rt-B
        ipv4CidrBlock: 10.0.24.32/27
      - name: Network-Boundary-TgwAttach-A
        availabilityZone: a
        routeTable: Network-Boundary-TgwAttach-Rt-A
        ipv4CidrBlock: 10.0.31.208/28
      - name: Network-Boundary-TgwAttach-B
        availabilityZone: b
        routeTable: Network-Boundary-TgwAttach-Rt-B
        ipv4CidrBlock: 10.0.31.224/28
    natGateways:
      - name: Network-Boundary-NatGw-A
        subnet: Network-Boundary-Untrust-A
      - name: Network-Boundary-NatGw-B
        subnet: Network-Boundary-Untrust-B
    transitGatewayAttachments:
      - name: Network-Boundary
        transitGateway:
          name: Network-Main
          account: Network
        routeTableAssociations:
          - Network-Main-Network-Boundary
        routeTablePropagations:
          - Network-Main-Internal
          - Network-Main-SharedServices-Main
        subnets:
          - Network-Boundary-TgwAttach-A
          - Network-Boundary-TgwAttach-B

  # Shared Services Account
  # SharedServices-Main VPC
  # This vpc creates 3 subnets in each AZs
  # Subnets includes app, data and tgw attach.
  ### This vpc host sharedsevices applications.
  - name: SharedServices-Main
    account: SharedServices
    region: *HOME_REGION
    cidrs:
      - 10.1.0.0/20
    internetGateway: false
    enableDnsHostnames: true
    enableDnsSupport: true
    instanceTenancy: default
    routeTables:
      - name: SharedServices-Main-App-Rt-A
        routes:
          - name: TgwRoute
            destination: 0.0.0.0/0
            type: transitGateway
            target: Network-Main
      - name: SharedServices-Main-App-Rt-B
        routes:
          - name: TgwRoute
            destination: 0.0.0.0/0
            type: transitGateway
            target: Network-Main
      - name: SharedServices-Main-Database-Rt-A
      - name: SharedServices-Main-Database-Rt-B
      - name: SharedServices-Main-TgwAttach-Rt-A
      - name: SharedServices-Main-TgwAttach-Rt-B
    subnets:
      - name: SharedServices-Main-App-A
        availabilityZone: a
        routeTable: SharedServices-Main-App-Rt-A
        ipv4CidrBlock: 10.1.0.0/22
      - name: SharedServices-Main-App-B
        availabilityZone: b
        routeTable: SharedServices-Main-App-Rt-B
        ipv4CidrBlock: 10.1.4.0/22
      - name: SharedServices-Main-Database-A
        availabilityZone: a
        routeTable: SharedServices-Main-Database-Rt-A
        ipv4CidrBlock: 10.1.12.0/24
      - name: SharedServices-Main-Database-B
        availabilityZone: b
        routeTable: SharedServices-Main-Database-Rt-B
        ipv4CidrBlock: 10.1.13.0/24
      - name: SharedServices-Main-TgwAttach-A
        availabilityZone: a
        routeTable: SharedServices-Main-TgwAttach-Rt-A
        ipv4CidrBlock: 10.1.15.208/28
      - name: SharedServices-Main-TgwAttach-B
        availabilityZone: b
        routeTable: SharedServices-Main-TgwAttach-Rt-B
        ipv4CidrBlock: 10.1.15.224/28
    transitGatewayAttachments:
      - name: SharedServices-Main
        transitGateway:
          name: Network-Main
          account: Network
        routeTableAssociations:
          - Network-Main-SharedServices-Main
        routeTablePropagations:
          - Network-Main-Internal
          - Network-Main-Network-Boundary
        subnets:
          - SharedServices-Main-TgwAttach-A
          - SharedServices-Main-TgwAttach-B
  # Development (1 AZ)
  - name: Development-Main
    account: Development
    region: *HOME_REGION
    cidrs:
      - 10.10.0.0/20
    enableDnsHostnames: true
    enableDnsSupport: true
    instanceTenancy: default
    subnets:
      - name: Dev-App-A
        availabilityZone: a
        routeTable: Dev-App-Rt-A
        ipv4CidrBlock: 10.10.0.0/24
      - name: Dev-DB-A
        availabilityZone: a
        routeTable: Dev-DB-Rt-A
        ipv4CidrBlock: 10.10.1.0/24
      - name: Dev-TgwAttach-A
        availabilityZone: a
        routeTable: Dev-TgwAttach-Rt-A
        ipv4CidrBlock: 10.10.3.240/28
    routeTables:
      - name: Dev-App-Rt-A
      - name: Dev-DB-Rt-A
      - name: Dev-TgwAttach-Rt-A
    transitGatewayAttachments:
      - name: DevelopmentTGWAttachment
        transitGateway:
          name: Network-Main
          account: Network
        routeTableAssociations:
          - Network-Main-Internal
        routeTablePropagations:
          - Network-Main-SharedServices-Main
          - Network-Main-Network-Boundary
        subnets:
          - Dev-TgwAttach-A

  # QA (1 AZ)
  - name: QA-Main
    account: QA
    region: *HOME_REGION
    cidrs:
      - 10.20.0.0/20
    enableDnsHostnames: true
    enableDnsSupport: true
    instanceTenancy: default
    subnets:
      - name: QA-App-A
        availabilityZone: a
        routeTable: QA-App-Rt-A
        ipv4CidrBlock: 10.20.0.0/24
      - name: QA-DB-A
        availabilityZone: a
        routeTable: QA-DB-Rt-A
        ipv4CidrBlock: 10.20.1.0/24
      - name: QA-TgwAttach-A
        availabilityZone: a
        routeTable: QA-TgwAttach-Rt-A
        ipv4CidrBlock: 10.20.3.240/28
    routeTables:
      - name: QA-App-Rt-A
      - name: QA-DB-Rt-A
      - name: QA-TgwAttach-Rt-A
    transitGatewayAttachments:
      - name: QATGWAttachment
        transitGateway:
          name: Network-Main
          account: Network
        routeTableAssociations:
          - Network-Main-Internal
        routeTablePropagations:
          - Network-Main-SharedServices-Main
          - Network-Main-Network-Boundary
        subnets:
          - QA-TgwAttach-A

  # Stage01 (2 AZs)
  - name: Stage01-Main
    account: Stage01
    region: *HOME_REGION
    cidrs:
      - 10.30.0.0/20
    enableDnsHostnames: true
    enableDnsSupport: true
    instanceTenancy: default
    subnets:
      - name: Stage-App-A
        availabilityZone: a
        routeTable: Stage-App-Rt-A
        ipv4CidrBlock: 10.30.0.0/24
      - name: Stage-App-B
        availabilityZone: b
        routeTable: Stage-App-Rt-B
        ipv4CidrBlock: 10.30.4.0/24
      - name: Stage-DB-A
        availabilityZone: a
        routeTable: Stage-DB-Rt-A
        ipv4CidrBlock: 10.30.1.0/24
      - name: Stage-DB-B
        availabilityZone: b
        routeTable: Stage-DB-Rt-B
        ipv4CidrBlock: 10.30.5.0/24
      - name: Stage-TgwAttach-A
        availabilityZone: a
        routeTable: Stage-TgwAttach-Rt-A
        ipv4CidrBlock: 10.30.3.240/28
      - name: Stage-TgwAttach-B
        availabilityZone: b
        routeTable: Stage-TgwAttach-Rt-B
        ipv4CidrBlock: 10.30.7.240/28
    routeTables:
      - name: Stage-App-Rt-A
      - name: Stage-App-Rt-B
      - name: Stage-DB-Rt-A
      - name: Stage-DB-Rt-B
      - name: Stage-TgwAttach-Rt-A
      - name: Stage-TgwAttach-Rt-B
    transitGatewayAttachments:
      - name: Stage01TGWAttachment
        transitGateway:
          name: Network-Main
          account: Network
        routeTableAssociations:
          - Network-Main-Internal
        routeTablePropagations:
          - Network-Main-SharedServices-Main
          - Network-Main-Network-Boundary
        subnets:
          - Stage-TgwAttach-A
          - Stage-TgwAttach-B

  # Production (2 AZs)
  - name: Production-Main
    account: Production
    region: *HOME_REGION
    cidrs:
      - 10.40.0.0/20
    enableDnsHostnames: true
    enableDnsSupport: true
    instanceTenancy: default
    subnets:
      - name: Prod-App-A
        availabilityZone: a
        routeTable: Prod-App-Rt-A
        ipv4CidrBlock: 10.40.0.0/24
      - name: Prod-App-B
        availabilityZone: b
        routeTable: Prod-App-Rt-B
        ipv4CidrBlock: 10.40.4.0/24
      - name: Prod-DB-A
        availabilityZone: a
        routeTable: Prod-DB-Rt-A
        ipv4CidrBlock: 10.40.1.0/24
      - name: Prod-DB-B
        availabilityZone: b
        routeTable: Prod-DB-Rt-B
        ipv4CidrBlock: 10.40.5.0/24
      - name: Prod-TgwAttach-A
        availabilityZone: a
        routeTable: Prod-TgwAttach-Rt-A
        ipv4CidrBlock: 10.40.3.240/28
      - name: Prod-TgwAttach-B
        availabilityZone: b
        routeTable: Prod-TgwAttach-Rt-B
        ipv4CidrBlock: 10.40.7.240/28
    routeTables:
      - name: Prod-App-Rt-A
      - name: Prod-App-Rt-B
      - name: Prod-DB-Rt-A
      - name: Prod-DB-Rt-B
      - name: Prod-TgwAttach-Rt-A
      - name: Prod-TgwAttach-Rt-B
    transitGatewayAttachments:
      - name: ProductionTGWAttachment
        transitGateway:
          name: Network-Main
          account: Network
        routeTableAssociations:
          - Network-Main-Internal
        routeTablePropagations:
          - Network-Main-SharedServices-Main
          - Network-Main-Network-Boundary
        subnets:
          - Prod-TgwAttach-A
          - Prod-TgwAttach-B

##############################################################
# Global configuration for VPC flow logs                     #
# Where there is no flow log configuration defined with VPC  #
# this configuration will be used for flow log configuration #
##############################################################
vpcFlowLogs:
  trafficType: ALL
  maxAggregationInterval: 600
  destinations:
    - cloud-watch-logs
  destinationsConfig:
    cloudWatchLogs:
      retentionInDays: 30
  defaultFormat: false
  customFields:
    - version
    - account-id
    - interface-id
    - srcaddr
    - dstaddr
    - srcport
    - dstport
    - protocol
    - packets
    - bytes
    - start
    - end
    - action
    - log-status
    - vpc-id
    - subnet-id
    - instance-id
    - tcp-flags
    - type
    - pkt-srcaddr
    - pkt-dstaddr
    - region
    - az-id
    - pkt-src-aws-service
    - pkt-dst-aws-service
    - flow-direction
    - traffic-path
